### ISSUE TITLE
Erlang OTP 23-24 support

### ISSUE THREAD

**Issue by mattathompson** [pushex-project/pushex#42]
## Expected Behavior

Upgraded dep support for OTP 23/24 in order to take advantages of new cert capabilities as well as avoid issues with cert expiration happening October 1st.

## Context

We need to be able to upgrade our erlang OTP version in order to mitigate issues that'll be cause by _Let’s Encrypt_ root cert expiration. 

https://blog.voltone.net/post/30

I'd be happy to help move this along if needed.

**Comment by sb8244** [comment]
I had started an update a long time ago but phoenix 1.5 was still RC and I forgot about it. I just updated branch and things look good. Waiting for test matrix to pass (added OTP 24 latest / Elixir 1.12.3), and will run my own QA.

https://github.com/pushex-project/pushex/pull/40

**Comment by sb8244** [comment]
@mattathompson I just published 2.0.0 and JS 0.2.0 that upgrades everything to the latest version. See the changelog.md for the upgrade notes, there are a few small changes needed.

Please re-open if you run into any issues.
